### ISSUE TITLE
Using Eclipse Paho client library?

### ISSUE THREAD

**Issue by JokerQyou** [andycampbell92/mqtt-socketio#1]
I've read some codes of this repository, and it seems you were using an old version of Paho client library. Is that right? 
I've used the Paho library recently, and the constructor is like this:

```js
var client = Paho.MQTT.Client(broker_host, broker_port, client_id);
```

I did not dive deep into the Paho library, though. But I think it might be better if this repository uses the newest stable version of Paho library. 
Thanks for this repo! I might use it in my projects, is that okay?

**Comment by andycampbell92** [comment]
You're probably right, I will update the repo when I get some spare time to use the latest version of the Paho library. Thanks for letting me know.

Of course! Keep in mind that if a client uses the mqtt bridge then QOS is lost as the bridge will show as the endpoint to the mqtt broker instead of the client. So the message will show as delivered when the message reaches the bridge not the client.

Please let me know if you do use it in any projects I will link to them here if that is ok with you.

**Comment by JokerQyou** [comment]
Very quick reply. And thanks a lot!

**Comment by JokerQyou** [comment]
And speaking of using this repo, I'm actually not a Node.js user (I use Python most of the time), and I found myself stuck in the bridge codes. 
I've made some small changes to the `mqtt-socketio.js

**Comment by JokerQyou** [comment]
Hi! It's me again. Sorry to disturb you, but I'm having problem running your test. 
I'm using node version 0.10.35 x64 on Windows 7 x64 system, and used following commands to install dependencies:

```shell
npm install mqtt
npm install socket.io
npm install ascoltatori
```

and the full package list is: 

```
D:\Work\DO\mqtt-socketio-bridge
├─┬ ascoltatori@0.18.0
│ ├─┬ amqp@0.2.0
│ │ └── lodash@1.3.1
│ ├── async@0.9.0
│ ├─┬ debug@2.1.1
│ │ └── ms@0.6.2
│ ├── eventemitter2@0.4.14
│ ├─┬ mongodb@1.4.28
│ │ ├─┬ bson@0.2.16
│ │ │ └── nan@1.3.0
│ │ ├─┬ kerberos@0.0.7
│ │ │ └── nan@1.3.0
│ │ └─┬ readable-stream@1.0.33
│ │   ├── core-util-is@1.0.1
│ │   ├── inherits@2.0.1
│ │   ├── isarray@0.0.1
│ │   └── string_decoder@0.10.31
│ ├── node-uuid@1.4.2
│ ├── qlobber@0.3.9
│ ├─┬ qlobber-fsq@0.1.1
│ │ ├── async@0.2.10
│ │ ├── buffertools@2.0.1
│ │ ├── fs-ext@0.3.2
│ │ └── graceful-fs@2.0.3
│ ├── redis@0.12.1
│ └─┬ zmq@2.8.0
│   ├── bindings@1.1.1
│   └── nan@1.3.0
├─┬ mqtt@0.3.13
│ └─┬ readable-stream@1.0.33
│   ├── core-util-is@1.0.1
│   ├── inherits@2.0.1
│   ├── isarray@0.0.1
│   └── string_decoder@0.10.31
└─┬ socket.io@1.2.1
  ├── debug@0.7.4
  ├─┬ engine.io@1.4.3
  │ ├── base64id@0.1.0
  │ ├─┬ debug@1.0.3
  │ │ └── ms@0.6.2
  │ ├─┬ engine.io-parser@1.1.0
  │ │ ├── after@0.8.1
  │ │ ├── arraybuffer.slice@0.0.6
  │ │ ├── base64-arraybuffer@0.1.2
  │ │ ├── blob@0.0.2
  │ │ └── utf8@2.0.0
  │ └─┬ ws@0.5.0
  │   ├── nan@1.4.1
  │   ├── options@0.0.6
  │   └── ultron@1.0.1
  ├─┬ has-binary-data@0.1.3
  │ └── isarray@0.0.1
  ├─┬ socket.io-adapter@0.3.1
  │ ├─┬ debug@1.0.2
  │ │ └── ms@0.6.2
  │ └── object-keys@1.0.1
  ├─┬ socket.io-client@1.2.1
  │ ├── component-bind@1.0.0
  │ ├── component-emitter@1.1.2
  │ ├─┬ engine.io-client@1.4.3
  │ │ ├── component-inherit@0.0.3
  │ │ ├─┬ debug@1.0.4
  │ │ │ └── ms@0.6.2
  │ │ ├─┬ engine.io-parser@1.1.0
  │ │ │ ├── after@0.8.1
  │ │ │ ├── arraybuffer.slice@0.0.6
  │ │ │ ├── base64-arraybuffer@0.1.2
  │ │ │ ├── blob@0.0.2
  │ │ │ └── utf8@2.0.0
  │ │ ├─┬ has-cors@1.0.3
  │ │ │ └── global@2.0.1
  │ │ ├─┬ parsejson@0.0.1
  │ │ │ └─┬ better-assert@1.0.2
  │ │ │   └── callsite@1.0.0
  │ │ ├─┬ parseqs@0.0.2
  │ │ │ └─┬ better-assert@1.0.2
  │ │ │   └── callsite@1.0.0
  │ │ ├─┬ parseuri@0.0.4
  │ │ │ └─┬ better-assert@1.0.2
  │ │ │   └── callsite@1.0.0
  │ │ ├─┬ ws@0.4.31
  │ │ │ ├── commander@0.6.1
  │ │ │ ├── nan@0.3.2
  │ │ │ ├── options@0.0.6
  │ │ │ └── tinycolor@0.0.1
  │ │ └── xmlhttprequest@1.5.0
  │ ├─┬ has-binary@0.1.5
  │ │ └── isarray@0.0.1
  │ ├── indexof@0.0.1
  │ ├── object-component@0.0.3
  │ ├─┬ parseuri@0.0.2
  │ │ └─┬ better-assert@1.0.2
  │ │   └── callsite@1.0.0
  │ └── to-array@0.1.3
  └─┬ socket.io-parser@2.2.2
    ├── benchmark@1.0.0
    ├── component-emitter@1.1.2
    ├── isarray@0.0.1
    └── json3@3.2.6
```

And I ran this bridge this way: 

```shell
node mqtt-socketio-bridge.js
```

And serves the `test.html` at `http//127.0.0.1:8000` as static file. 
The test page was able to connect to the Socket.IO bridge, though. But the bridge does not output any log, which might indicates that it never connects to the MQTT broker. And no message could be received through this bridge. 

I don't know what is happening, it seems quite confusing. I'd be really appreciated if you could help me on this. Thanks!

**Comment by JokerQyou** [comment]
Damn it! I should have checked more carefully... It's because I'm having very wrong configuration (wrong MQTT port), and `ascoltatori` would not output any error messages. 
So, really sorry for that. :(

**Comment by andycampbell92** [comment]
No problem at all. I'm hoping to get some time to look at the library over
the weekend. Hopefully I can write a getting started guide for others.
